apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: tools
      #image: maven:3.6.3-jdk-11
      #custom image
      image: caternberg/ci-toolbox
      command:
        - cat
      tty: true
    - name: build
      image: maven:3.6.3-jdk-11
      #custom image
      #image: caternberg/ci-toolbox
      command:
        - cat
      tty: true