apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: tools
      #image: maven:3.6.3-jdk-11
      #custom image
      image: caternberg/ci-toolbox
      command:
        - cat
      tty: true
      volumeMounts:
        - name: config-volume
          mountPath: /usr/local/bin
    - name: build
      image: maven:3.6.3-jdk-11
      command:
        - cat
      tty: true
      volumeMounts:
        - name: config-volume
          mountPath: /usr/local/bin
  volumes:
    #https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: pod-build-scripts
        defaultMode: 0744